language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
dist: xenial
addons:
  apt:
    packages:
    - cmake
# command to install dependencies
cache:
  - pip
install:
  - make requirements
  - python setup.py install

script:
  - make flake
  - make black-check
  - make test-docs
  - make test-handler
  - make test-middleware
  - make test-placebo
  - make test-async
  - make test-general

after_success:
  coveralls
notifications:
  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
